services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
    secrets:
      - wordpress_db_host
      - wordpress_db_user
      - wordpress_db_password
      - wordpress_db_name
    environment:
      WORDPRESS_DB_HOST_FILE: /run/secrets/wordpress_db_host
      WORDPRESS_DB_USER_FILE: /run/secrets/wordpress_db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME_FILE: /run/secrets/wordpress_db_name
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      retries: 5
      timeout: 5s

  mysql:
    image: mysql:8.0
    restart: always
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 10s
      retries: 5
      timeout: 5s

secrets:
  wordpress_db_host:
    file: ./secrets/wordpress/wordpress_db_host.txt
  wordpress_db_user:
    file: ./secrets/wordpress/wordpress_db_user.txt
  wordpress_db_name:
    file: ./secrets/wordpress/wordpress_db_name.txt
  wordpress_db_password:
    file: ./secrets/wordpress/wordpress_db_password.txt

  mysql_database:
    file: ./secrets/mysql/mysql_database.txt
  mysql_password:
    file: ./secrets/mysql/mysql_password.txt
  mysql_user:
    file: ./secrets/mysql/mysql_user.txt

volumes:
  wordpress:
  db:

networks:
  frontend:
  backend:
